var config = {
    NUM_SECTORS: 10,
    MIN_NEIGHBORS: 2,
    MAX_NEIGHBORS: 2,
    MIN_CLUSTERS:  5,
    MIN_SECTORS_PER_CLUSTER: 2,
    MAX_SECTORS_PER_CLUSTER: 2,
    ONE_WAY_RATIO: .15, // 5% of sectors should be one-way
    TWO_WAY_RATIO: .3,  // 30% of sectors should have two-way connections

    MIN_TRADERS: 3,
    MAX_TRADERS: 4,
    
    SHOP_DENSITY         : 0.4, // 40% of sectors have shops
    SHOP_MIN_BANKROLL    : 10000,
    SHOP_AVERAGE_BANKROLL: 500000,

    PRICE_FUEL_STANDARD     : 100,
    PRICE_ORGANICS_STANDARD : 500,
    PRICE_EQUIPMENT_STANDARD: 2500,

    PRICE_FUEL_MIN     : 50,
    PRICE_ORGANICS_MIN : 150,
    PRICE_EQUIPMENT_MIN: 750,

    INVENTORY_FUEL_STANDARD     : 100,
    INVENTORY_ORGANICS_STANDARD : 50,
    INVENTORY_EQUIPMENT_STANDARD: 25,

    INVENTORY_FUEL_MIN     : 25,
    INVENTORY_ORGANICS_MIN : 10,
    INVENTORY_EQUIPMENT_MIN: 0
};

module.exports = config;